wip

diff --git a/.github/workflows/update-snapshots.yml b/.github/workflows/update-snapshots.yml
--- a/.github/workflows/update-snapshots.yml
+++ b/.github/workflows/update-snapshots.yml
@@ -18,19 +18,19 @@ jobs:
 
     steps:
 
-      - name: Verify branch exists
-        run: |
-          if ! git ls-remote --exit-code origin ${{ github.event.inputs.target-branch }}; then
-            echo "❌ ERROR: Branch '${{ github.event.inputs.target-branch }}' does not exist on origin. DEV BRANCH"
-            exit 1
-          fi
-
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.target-branch }}
           token: ${{ secrets.GITHUB_TOKEN }}
           fetch-depth: 0
+
+      - name: Verify branch exists
+        run: |
+          if ! git ls-remote --exit-code origin ${{ github.event.inputs.target-branch }}; then
+            echo "❌ ERROR: Branch '${{ github.event.inputs.target-branch }}' does not exist on origin. DEV BRANCH"
+            exit 1
+          fi
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v3
